version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "milan.kappen"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "github.com/some-ignored/package"
