builds:
  - env:
      - CGO_ENABLED=1
      - GOAMD64=v3
      - XX_CC_PREFER_STATIC_LINKER=1
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -v
    ldflags:
      - -s -w
      - -X h3s/internal/version.Version={{ .Version }}
      - -X h3s/internal/version.Commit={{ .Commit }}
      - -X 'h3s/internal/version.GoVersion={{ .Env.GOVERSION }}'
    tags:
      - netgo
      - osusergo
    builder: docker
    docker:
      image: crazymax/goreleaser-xx:latest
      volumes:
        - /tmp/build:/tmp/build
    gobinary: "go"
    no_unique_dist_dir: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

release:
  github:
    owner: imamik
    name: h3s
  draft: false
  prerelease: false
  extra_files:
    - glob: LICENSE.txt
