before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test -v ./...

builds:
  - id: h3s
    binary: h3s
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X h3s/internal/version.Version={{ .Version }}
      - -X h3s/internal/version.Commit={{ .Commit }}
      - -X 'h3s/internal/version.GoVersion={{ .Env.GOVERSION }}'
    tags:
      - netgo
      - osusergo

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: imamik
    name: h3s
  draft: false
  prerelease: false
  extra_files:
    - glob: LICENSE.txt
