apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apiserver-ingress
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  ingressClassName: traefik
  rules:
    - host: kubectl.storyteller.plus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  name: websecure