apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  version: "{{ .Version }}"
  repo: https://charts.jetstack.io
  targetNamespace: "{{ .Namespace }}"
  createNamespace: true
  valuesContent: |-
    crds:
      enabled: true
    webhook:
      enabled: true
    cainjector:
      enabled: true
    startupapicheck:
      enabled: true
    ingressShim:
      enabled: true