apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-hetzner
  namespace: kube-system
spec:
  chart: cert-manager-webhook-hetzner
  version: "{{ .CertManagerHetznerVersion }}"
  repo: https://vadimkim.github.io/cert-manager-webhook-hetzner
  targetNamespace: "{{ .CertManagerNamespace }}"
  set:
    groupName: "{{ .Domain }}"