name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      fetch-depth: 0

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.24.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: go$(go version | cut -d' ' -f3) 